---
name: redis
director_uuid: e95c4be3-dfce-45ef-8e4a-59a2d8d92c4e

release:
  name: redis-ha
  version: latest

compilation:
  workers: 4
  network: compile
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4

networks:
- name: default
  subnets:
<% (0..63).each_with_index.map do |i| %>
  - range: 10.244.1.<%= i*4 %>/30
    reserved:
      - 10.244.1.<%= i*4 + 1 %>
    static:
      - 10.244.1.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>
<% (0..63).each_with_index.map do |i| %>
  - range: 10.244.2.<%= i*4 %>/30
    reserved:
      - 10.244.2.<%= i*4 + 1 %>
    cloud_properties:
      name: random
<% end %>
- name: compile
  subnets:
<% (0..63).each_with_index.map do |i| %>
  - range: 10.244.0.<%= i*4 %>/30
    reserved:
      - 10.244.0.<%= i*4 + 1 %>
    cloud_properties:
      name: random
<% end %>

resource_pools:
- name: common
  network: default
  size: 3
  stemcell:
    name: bosh-stemcell
    version: latest
  cloud_properties: {}

jobs:
- name: redis-master
  template: redis
  instances: 1
  resource_pool: common
  networks:
  - name: default
    default:
    - dns
    - gateway
    static_ips:
      - 10.244.1.2
  properties:
    redis:
      replication:
        master:
          enabled: true

- name: redis-slave
  template: redis
  instances: 2
  resource_pool: common
  networks:
  - name: default
    default:
    - dns
    - gateway
    static_ips:
      - 10.244.1.6
      - 10.244.1.10

properties:
  redis:
    replication:
      enabled: true
      master:
        address: 10.244.1.2
    password: hello1